// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: btlmassage.proto

package btlmassagerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackDustRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HtlcIndex     uint64                 `protobuf:"varint,1,opt,name=htlcIndex,proto3" json:"htlcIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackDustRequest) Reset() {
	*x = BackDustRequest{}
	mi := &file_btlmassage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackDustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackDustRequest) ProtoMessage() {}

func (x *BackDustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btlmassage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackDustRequest.ProtoReflect.Descriptor instead.
func (*BackDustRequest) Descriptor() ([]byte, []int) {
	return file_btlmassage_proto_rawDescGZIP(), []int{0}
}

func (x *BackDustRequest) GetHtlcIndex() uint64 {
	if x != nil {
		return x.HtlcIndex
	}
	return 0
}

type BackDustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDust        bool                   `protobuf:"varint,1,opt,name=isDust,proto3" json:"isDust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackDustResponse) Reset() {
	*x = BackDustResponse{}
	mi := &file_btlmassage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackDustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackDustResponse) ProtoMessage() {}

func (x *BackDustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btlmassage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackDustResponse.ProtoReflect.Descriptor instead.
func (*BackDustResponse) Descriptor() ([]byte, []int) {
	return file_btlmassage_proto_rawDescGZIP(), []int{1}
}

func (x *BackDustResponse) GetIsDust() bool {
	if x != nil {
		return x.IsDust
	}
	return false
}

var File_btlmassage_proto protoreflect.FileDescriptor

const file_btlmassage_proto_rawDesc = "" +
	"\n" +
	"\x10btlmassage.proto\x12\rbtlchannelrpc\"/\n" +
	"\x0fBackDustRequest\x12\x1c\n" +
	"\thtlcIndex\x18\x01 \x01(\x04R\thtlcIndex\"*\n" +
	"\x10BackDustResponse\x12\x16\n" +
	"\x06isDust\x18\x01 \x01(\bR\x06isDust2Y\n" +
	"\n" +
	"BtlMassage\x12K\n" +
	"\bBackDust\x12\x1e.btlchannelrpc.BackDustRequest\x1a\x1f.btlchannelrpc.BackDustResponseB>Z<github.com/lightninglabs/taproot-assets/taprpc/btlmassagerpcb\x06proto3"

var (
	file_btlmassage_proto_rawDescOnce sync.Once
	file_btlmassage_proto_rawDescData []byte
)

func file_btlmassage_proto_rawDescGZIP() []byte {
	file_btlmassage_proto_rawDescOnce.Do(func() {
		file_btlmassage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btlmassage_proto_rawDesc), len(file_btlmassage_proto_rawDesc)))
	})
	return file_btlmassage_proto_rawDescData
}

var file_btlmassage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_btlmassage_proto_goTypes = []any{
	(*BackDustRequest)(nil),  // 0: btlchannelrpc.BackDustRequest
	(*BackDustResponse)(nil), // 1: btlchannelrpc.BackDustResponse
}
var file_btlmassage_proto_depIdxs = []int32{
	0, // 0: btlchannelrpc.BtlMassage.BackDust:input_type -> btlchannelrpc.BackDustRequest
	1, // 1: btlchannelrpc.BtlMassage.BackDust:output_type -> btlchannelrpc.BackDustResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_btlmassage_proto_init() }
func file_btlmassage_proto_init() {
	if File_btlmassage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btlmassage_proto_rawDesc), len(file_btlmassage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btlmassage_proto_goTypes,
		DependencyIndexes: file_btlmassage_proto_depIdxs,
		MessageInfos:      file_btlmassage_proto_msgTypes,
	}.Build()
	File_btlmassage_proto = out.File
	file_btlmassage_proto_goTypes = nil
	file_btlmassage_proto_depIdxs = nil
}
